### ISSUE TITLE
Fingerprint unlock unavailable after user switching

### ISSUE THREAD

**Issue by MaximeCrp** [GrapheneOS/grapheneos.org#699] opened 2023-07-03 23:34 UTC
I have been facing what I think is a weird bug for a few days (before and after latest updates).

- Be logged in in main user (haven't tested from another user) with fingerprint unlock activated
- Switch user to secondary user with fingerprint unlock activated
- Unlock secondary user
- End secondary user session
- Unlock screen for main user never shows possibility to unlock with fingerprint (even after several successful unlocks with code)
- "End session" button sometimes appear on lock screen of main user
- Click "end session" button on main user lock screen
- Screen flashes black
- Fingerprint unlock now available and working

If needed, I can look into recording the screen through this process
Available to look further into this and help with the solution

Pixel 7a

**Comment by thestinger** [comment] 2023-07-03 23:40
Upstream issue and duplicate of https://github.com/GrapheneOS/grapheneos.org/issues/548.

**Closed by thestinger** 2023-07-03 23:40 UTC

**Comment by MaximeCrp** [comment] 2023-07-03 23:48
@thestinger the behaviour is quite different from what was reported in #548 
Can you please link to AOSP IssueTrack ticket to check this is the same one? 
Thank you
